-- =============================================================
-- UPDATE candidates unit/department alignment
-- Run this in the Supabase SQL Editor
-- =============================================================

-- First, let's preview what will be updated (DRY RUN)
-- Uncomment the SELECT block below to preview before running the UPDATE

/*
SELECT c.email, c.unit AS current_unit, mapping.new_unit
FROM candidates c
JOIN (VALUES
  ('saifullahi.idris@babbangona.com', 'Operator Success'),
  ('vincent.odigo@babbangona.com', 'Operator Success')
  -- ... truncated for preview
) AS mapping(email, new_unit) ON LOWER(c.email) = LOWER(mapping.email)
WHERE c.unit IS DISTINCT FROM mapping.new_unit;
*/

-- =============================================================
-- ACTUAL UPDATE
-- =============================================================
UPDATE candidates
SET unit = mapping.new_unit,
    updated_at = NOW()
FROM (VALUES
  ('saifullahi.idris@babbangona.com', 'Operator Success'),
  ('vincent.odigo@babbangona.com', 'Operator Success'),
  ('isah.saidu@babbangona.com', 'Operator Success'),
  ('george.osagiri@babbangona.com', 'Operator Success'),
  ('rehoboth.iyasele@babbangona.com', 'Enterprise Systems Engineering'),
  ('adesayo.lawson@babbangona.com', 'Enterprise Systems Engineering'),
  ('kingsley.aruya@babbangona.com', 'Internal Audit'),
  ('shittu.temidayo@babbangona.com', 'Enterprise Systems Engineering'),
  ('lanre.shittu@babbangona.com', 'Enterprise Systems Engineering'),
  ('simi.shote@babbangona.com', 'Enterprise Systems Engineering'),
  ('junior.oduberu@babbangona.com', 'Enterprise Systems Engineering'),
  ('segun.orimolade@babbangona.com', 'Enterprise Systems Product'),
  ('felix.bello@babbangona.com', 'Enterprise Systems Engineering'),
  ('dorcas.kyana@babbangona.com', 'Internal Audit'),
  ('emmanuel.adah@babbangona.com', 'Last Mile Logistics'),
  ('lukman.adebisi@babbangona.com', 'Enterprise Systems Product'),
  ('bitrus.audu@babbangona.com', 'Last Mile Logistics'),
  ('muhammed.yakubu@babbangona.com', 'Last Mile Logistics'),
  ('uzochukwu.nkamuke@babbangona.com', 'Enterprise Systems Product'),
  ('alpha.monday@babbangona.com', 'Enterprise Systems Product'),
  ('benjamin.oriaje@babbangona.com', 'Inventory Control'),
  ('kclean.uzoukwu@babbangona.com', 'Enterprise Systems Engineering'),
  ('hammed.odiwo@babbangona.com', 'Last Mile Logistics'),
  ('victory.igwe@babbangona.com', 'Inventory Control'),
  ('akintomiwa.odusanya@babbangona.com', 'Data'),
  ('raji.adeleye@babbangona.com', 'Performance Acceleration'),
  ('sherif.adebiyi@babbangona.com', 'Inventory Control'),
  ('nurudeen.ibrahim@babbangona.com', 'Data'),
  ('damilare.adeyoyin@babbangona.com', 'Data'),
  ('ikechukwu.ngwu@babbangona.com', 'Data'),
  ('thankgodbature.bature@babbangona.com', 'Last Mile Logistics'),
  ('bashir.olabanji@babbangona.com', 'Last Mile Logistics'),
  ('chukwuma.ezeanyim@babbangona.com', 'Last Mile Logistics'),
  ('david.eneogwe@babbangona.com', 'Internal Audit'),
  ('daniel.ori@babbangona.com', 'Enterprise Systems Product'),
  ('henry.owoeye@babbangona.com', 'Last Mile Logistics'),
  ('betty.omotola@babbangona.com', 'Legal & Compliance'),
  ('daniel.ayodele@babbangona.com', 'Enterprise Systems Engineering'),
  ('aanu.badejo@babbangona.com', 'Internal Audit'),
  ('anas.saeed@babbangona.com', 'Last Mile Logistics'),
  ('anu.fajebe@babbangona.com', 'Finance Operations'),
  ('joel.john@babbangona.com', 'Last Mile Logistics'),
  ('mika.umar@babbangona.com', 'Last Mile Logistics'),
  ('ernest.abah@babbangona.com', 'Internal Audit'),
  ('lukman.balogun@babbangona.com', 'Enterprise Systems Engineering'),
  ('kosisochukwu.nwuba@babbangona.com', 'Finance Operations'),
  ('auwal.hadi@babbangona.com', 'Last Mile Logistics'),
  ('toluwani.oluwamuyiwa@babbangona.com', 'Enterprise Systems Product'),
  ('david.onyeali@babbangona.com', 'Data'),
  ('isaac.ubani@babbangona.com', 'Enterprise Systems Engineering'),
  ('edidiong.oni@babbangona.com', 'Enterprise Systems Product'),
  ('victoria.matthew@babbangona.com', 'Last Mile Logistics'),
  ('dahiru.isiyaku@babbangona.com', 'Last Mile Logistics'),
  ('victoria.batuk@babbangona.com', 'Inventory Control'),
  ('elohor.evwrujae@babbangona.com', 'Enterprise Systems Engineering'),
  ('david.inusa@babbangona.com', 'Operator Success'),
  ('thankgod.ichibe@babbangona.com', 'Operator Success'),
  ('daniel.odeh@babbangona.com', 'Last Mile Logistics'),
  ('joel.nwachi@babbangona.com', 'Last Mile Logistics'),
  ('wura.adebayo@babbangona.com', 'Enterprise Systems Product'),
  ('ahmed.mohammed@babbangona.com', 'Enterprise Systems Engineering'),
  ('victor.onipinsaiye@babbangona.com', 'Enterprise Systems Product'),
  ('agatha.mathew@babbangona.com', 'Sales'),
  ('abbas.hashim@babbangona.com', 'Sales'),
  ('ayuba.samaila@babbangona.com', 'Last Mile Logistics'),
  ('joshua.dauda@babbangona.com', 'Last Mile Logistics'),
  ('caleb.ndaka@babbangona.com', 'Last Mile Logistics'),
  ('eniola.ogunsakin@babbangona.com', 'Sales'),
  ('ayotomiwa.sosanya@babbangona.com', 'Finance Operations'),
  ('victor.ogunlusi@babbangona.com', 'Enterprise Systems Engineering'),
  ('matthew.manu@babbangona.com', 'Security Services'),
  ('korede.oseni@babbangona.com', 'Enterprise Systems Engineering'),
  ('musa.dauda@babbangona.com', 'Internal Audit'),
  ('nathaniel.oni@babbangona.com', 'Finance Operations'),
  ('deborah.adeleke@babbangona.com', 'Human Resources'),
  ('francis.adegbemi@babbangona.com', 'Data'),
  ('alvan.nwanorim@babbangona.com', 'Enterprise Systems Engineering'),
  ('chianugo.ononuju@babbangona.com', 'Enterprise Systems Engineering'),
  ('olamide.adeleye@babbangona.com', 'Enterprise Systems Engineering'),
  ('zainab.lawal@babbangona.com', 'Enterprise Systems Engineering'),
  ('yusuf.shehu@babbangona.com', 'Performance Acceleration'),
  ('ahmed.onibiyo@babbangona.com', 'Enterprise Systems Engineering'),
  ('zainab.akinwande@babbangona.com', 'Data'),
  ('abdulmateen.mamudu@babbangona.com', 'Enterprise Systems Product'),
  ('jonathan.ikwuonwu@babbangona.com', 'Enterprise Systems Engineering'),
  ('olawale.okemuyiwa@babbangona.com', 'Enterprise Systems Engineering'),
  ('obende.prince@babbangona.com', 'Performance Acceleration'),
  ('timi.adeleye@babbangona.com', 'Enterprise Systems Engineering'),
  ('usman.abubakar@babbangona.com', 'Performance Acceleration'),
  ('oluwatomisin.bello@babbangona.com', 'Enterprise Systems Engineering'),
  ('halimat.adebakin@babbangona.com', 'Enterprise Systems Engineering'),
  ('gaius.yusuf@babbangona.com', 'Performance Acceleration'),
  ('taiwo.ibitoye@babbangona.com', 'Enterprise Systems Engineering'),
  ('abdulfatah.yunus@babbangona.com', 'Performance Acceleration'),
  ('mendhie.imeh@babbangona.com', 'Enterprise Systems Engineering'),
  ('blessing.bello@babbangona.com', 'Enterprise Systems Product'),
  ('ekunsunmi.daniel@babbangona.com', 'Enterprise Systems Engineering'),
  ('emmanuel.olajumoke@babbangona.com', 'Enterprise Systems Engineering'),
  ('ramon.adisa@babbangona.com', 'Enterprise Systems Engineering'),
  ('ibukun.oyeniyi@babbangona.com', 'Enterprise Systems Engineering'),
  ('miracle.abbas@babbangona.com', 'Performance Acceleration'),
  ('israel.ocholi@babbangona.com', 'Performance Acceleration'),
  ('richard.daramola@babbangona.com', 'Enterprise Systems Product'),
  ('godswill.julius@babbangona.com', 'Enterprise Systems Product'),
  ('harris.dogara@babbangona.com', 'Security Services'),
  ('idris.mustapha@babbangona.com', 'Security Services'),
  ('emmanuella.uzochukwu@babbangona.com', 'Enterprise Systems Product'),
  ('nehemiah.yohanna@babbangona.com', 'Performance Acceleration'),
  ('chisomaga.ukaegbu@babbangona.com', 'Enterprise Systems Product'),
  ('ezekiel.dodo@babbangona.com', 'Operator Success'),
  ('wilson.idzi@babbangona.com', 'Internal Audit'),
  ('john.abiola@babbangona.com', 'Enterprise Systems Engineering'),
  ('bashir.tajuddeen@babbangona.com', 'Last Mile Logistics'),
  ('alubarika.menegbe@babbangona.com', 'Operator Success'),
  ('friday.lawal@babbangona.com', 'Last Mile Logistics'),
  ('ibukun.adeosun@babbangona.com', 'Enterprise Systems Engineering'),
  ('zachariah.bitrus@babbangona.com', 'Inventory Control'),
  ('aminchi.ephraim@babbangona.com', 'Last Mile Logistics'),
  ('barnabas.bulus@babbangona.com', 'Last Mile Logistics'),
  ('babangida.haruna@babbangona.com', 'Last Mile Logistics'),
  ('muktar.garba@babbangona.com', 'Internal Audit'),
  ('patience.aminu@babbangona.com', 'Performance Acceleration'),
  ('nimitariye.george@babbangona.com', 'Human Resources'),
  ('evelyn.ogunsakin@babbangona.com', 'Human Resources'),
  ('malik.orenuga@babbangona.com', 'Human Resources'),
  ('praise.dairo@babbangona.com', 'Human Resources'),
  ('ememobong.ema@babbangona.com', 'Human Resources'),
  ('racheal.adeyemo@babbangona.com', 'Human Resources'),
  ('edidiong.udoh@babbangona.com', 'Finance Operations'),
  ('sanctus.thomas@babbangona.com', 'Operator Success'),
  ('yushau.yahaya@babbangona.com', 'Operator Success'),
  ('umar.farukharuna@babbangona.com', 'Internal Audit'),
  ('taiwo.ige@babbangona.com', 'Performance Acceleration'),
  ('joan.aigbiremhon@babbangona.com', 'Finance Operations'),
  ('ayuba.rogo@babbangona.com', 'Internal Audit'),
  ('nicholas.obagunle@babbangona.com', 'Enterprise Systems Engineering'),
  ('taiwo.gogo-hassan@babbangona.com', 'Data'),
  ('abano.raymond@babbangona.com', 'Performance Acceleration'),
  ('joy.okeh@babbangona.com', 'Human Resources'),
  ('mathew.bitrus@babbangona.com', 'Operator Success'),
  ('azeez.bello@babbangona.com', 'Investor Relations'),
  ('anuoluwapo.ogunrinde@babbangona.com', 'Data'),
  ('finbar.asoegwu@babbangona.com', 'Human Resources'),
  ('joash.joseph@babbangona.com', 'Inventory Control'),
  ('jacqueline.alex-odunsi@babbangona.com', 'Enterprise Systems Product'),
  ('elizabeth.ajala@babbangona.com', 'Human Resources'),
  ('adeyemi.martins@babbangona.com', 'Internal Services'),
  ('prosper.kalu@babbangona.com', 'Enterprise Systems Engineering'),
  ('mercy.titus@babbangona.com', 'Investor Relations'),
  ('victor.okorie@babbangona.com', 'Inventory Control'),
  ('aminah.ademola@babbangona.com', 'Finance Operations'),
  ('olawale.akinokun@babbangona.com', 'Finance Operations'),
  ('teslim.adekunle@babbangona.com', 'Finance Operations'),
  ('patrick.echatah@babbangona.com', 'Human Resources'),
  ('sulaimon.salako@babbangona.com', 'Enterprise Systems Product'),
  ('jenifer.gbebikan@babbangona.com', 'Enterprise Systems Engineering'),
  ('joshua.akhidenor@babbangona.com', 'Enterprise Systems Engineering'),
  ('imisioluwa.jemisenia@babbangona.com', 'Legal & Compliance'),
  ('jerome.nzegbuna@babbangona.com', 'Enterprise Systems Product'),
  ('damilola.bakare@babbangona.com', 'Enterprise Systems Engineering'),
  ('bababo.ademehin@babbangona.com', 'Investor Relations'),
  ('ifeoma.okpara@babbangona.com', 'Enterprise Systems Engineering'),
  ('nofisat.soluade@babbangona.com', 'Finance Operations'),
  ('dele.akande@babbangona.com', 'Investor Relations'),
  ('moses.odunosho@babbangona.com', 'Enterprise Systems Engineering'),
  ('tobi.adeyemo@babbangona.com', 'Enterprise Systems Engineering'),
  ('tosin.akerele@babbangona.com', 'Enterprise Systems Engineering'),
  ('olukemi.olugbade@babbangona.com', 'Human Resources'),
  ('funmi.eluyera@babbangona.com', 'Data'),
  ('victor.nwokike@babbangona.com', 'Enterprise Systems Product'),
  ('ibukunoluwa.fateru@babbangona.com', 'Investor Relations'),
  ('isaac.olawale@babbangona.com', 'Enterprise Systems Engineering'),
  ('esther.oyewole@babbangona.com', 'Legal & Compliance'),
  ('ifeoluwa.folajimi@babbangona.com', 'Investor Relations'),
  ('yusuff.yusuff@babbangona.com', 'Operator Success'),
  ('kingsley.afuzobugwu@babbangona.com', 'Data'),
  ('abdulmaatin.lawal@babbangona.com', 'Enterprise Systems Engineering'),
  ('abdulazeez.kazir@babbangona.com', 'Operator Success'),
  ('adamu.muhammed@babbangona.com', 'Operator Success'),
  ('adewole.marcus@babbangona.com', 'Finance Operations'),
  ('jason.osikoya@babbangona.com', 'Enterprise Systems Engineering'),
  ('solomon.attah@babbangona.com', 'Operator Success'),
  ('auwal.umar@babbangona.com', 'Operator Success'),
  ('blessing.mamman@babbangona.com', 'Operator Success'),
  ('bilikisu.zubairu@babbangona.com', 'Performance Acceleration'),
  ('biliyaminu.bauna@babbangona.com', 'Operator Success'),
  ('blessing.audu@babbangona.com', 'Operator Success'),
  ('christiana.ritkangnga@babbangona.com', 'Internal Services'),
  ('daniel.iliya@babbangona.com', 'Operator Success'),
  ('daniel.yohanna@babbangona.com', 'Operator Success'),
  ('dare.ogunmoriye@babbangona.com', 'Operator Success'),
  ('dauda.masama@babbangona.com', 'Operator Success'),
  ('david.charles@babbangona.com', 'Operator Success'),
  ('derick.david@babbangona.com', 'Operator Success'),
  ('derin.bankole@babbangona.com', 'Enterprise Systems Engineering'),
  ('dickson.udeh@babbangona.com', 'Fleet Management'),
  ('domshak.istifanusdanyaro@babbangona.com', 'Member Success'),
  ('dorathy.christopher@babbangona.com', 'Internal Services'),
  ('dorcas.mathew@babbangona.com', 'Operator Success'),
  ('jamaldeen.olasupo@babbangona.com', 'Enterprise Systems Engineering'),
  ('elizabeth.madi@babbangona.com', 'Operator Success'),
  ('eunice.okereke@babbangona.com', 'Human Resources'),
  ('fuad.ajiboye@babbangona.com', 'Enterprise Systems Engineering'),
  ('aisha.shittu@babbangona.com', 'Performance Acceleration'),
  ('georgina.ezekiel@babbangona.com', 'Internal Services'),
  ('grace.umar@babbangona.com', 'Member Success'),
  ('hamisu.magaji@babbangona.com', 'Performance Acceleration'),
  ('ibukun.onaeko@babbangona.com', 'Legal & Compliance'),
  ('ikechukwu.chukwuemeka@babbangona.com', 'Finance Operations'),
  ('iliya.bako@babbangona.com', 'Fleet Management'),
  ('james.ekeledo@babbangona.com', 'Inventory Control'),
  ('jamilu.mustapha@babbangona.com', 'Operator Success'),
  ('jonah.gotau@babbangona.com', 'Performance Acceleration'),
  ('kayode.ojo@babbangona.com', 'Sales'),
  ('mathew.babalola@babbangona.com', 'Operator Success'),
  ('maureen.stephen@babbangona.com', 'Internal Services'),
  ('micah.ibrahim@babbangona.com', 'Operator Success'),
  ('mohammed.balarabe@babbangona.com', 'Operator Success'),
  ('babatunde.soetan@babbangona.com', 'Sales'),
  ('nancy.kuheps@babbangona.com', 'Operator Success'),
  ('shuni.peace@babbangona.com', 'Operator Success'),
  ('zanang.nathaniel@babbangona.com', 'Operator Success'),
  ('ayoola.aguda@babbangona.com', 'Data'),
  ('jumoke.adedeji@babbangona.com', 'Inventory Control'),
  ('zainab.jibril@babbangona.com', 'Operator Success'),
  ('chinenye.obi@babbangona.com', 'Human Resources'),
  ('victor.isokpehi@babbangona.com', 'Enterprise Systems Engineering'),
  ('ameh.oche@babbangona.com', 'Human Resources'),
  ('solomon.yusuf@babbangona.com', 'Data'),
  ('nuhu.shehu@babbangona.com', 'Operator Success'),
  ('ruth.fwah@babbangona.com', 'Internal Services'),
  ('tamarakro.prebor@babbangona.com', 'Enterprise Systems Engineering'),
  ('nurudeen.yusuf@babbangona.com', 'Operator Success'),
  ('ojochenemi.friday@babbangona.com', 'Operator Success'),
  ('ola.balogun@babbangona.com', 'Investor Relations'),
  ('oluwafemi.aleehile@babbangona.com', 'Operator Success'),
  ('iliya.emmanuel@babbangona.com', 'Internal Services'),
  ('paul.nti@babbangona.com', 'Operator Success'),
  ('rafiat.bashorun@babbangona.com', 'Finance Operations'),
  ('safiyanu.zakari@babbangona.com', 'Operator Success'),
  ('sagir.aliyu@babbangona.com', 'Performance Acceleration'),
  ('salome.odeh@babbangona.com', 'Operator Success'),
  ('sani.sabiu@babbangona.com', 'Operator Success'),
  ('segun.babatunde@babbangona.com', 'Sales'),
  ('shola.olusegun@babbangona.com', 'Inventory Control'),
  ('sim.jacob@babbangona.com', 'Operator Success'),
  ('haruna.yohanna@babbangona.com', 'Operator Success'),
  ('solomon.tor@babbangona.com', 'Operator Success'),
  ('sophy.abbas@babbangona.com', 'Internal Services'),
  ('blessing.ejiga@babbangona.com', 'Operator Success'),
  ('suleiman.magaji@babbangona.com', 'Internal Services'),
  ('tobi.bolarinde@babbangona.com', 'Investor Relations'),
  ('uche.okorie@babbangona.com', 'Enterprise Systems Engineering'),
  ('victoria.ikwu@babbangona.com', 'Operator Success'),
  ('serah.ishaku@babbangona.com', 'Operator Success'),
  ('yahaya.jafaru@babbangona.com', 'Operator Success'),
  ('yahuza.abubakar@babbangona.com', 'Operator Success')
) AS mapping(email, new_unit)
WHERE LOWER(candidates.email) = LOWER(mapping.email);
