// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrfiltyxdviefanplykg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZmlsdHl4ZHZpZWZhbnBseWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MTIxOTYsImV4cCI6MjA1OTM4ODE5Nn0.LBgnlsmNJSPzwglS4r1ewhh0CLVg_prVVcUVIdnUHZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);